app:
  httpPort: 8081
  httpUrl: localhost:8081
  rpcPort: 9002
  webSocketPort: 8088
  webSocketUrl: localhost:8088

redis:
  addr: "localhost:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConns: 30

log:
  dir: log
  name: bychat.log
  level: trace
  max_size: 100